### ISSUE TITLE
require is not defined  

### ISSUE THREAD

**Issue by Femina** [Max95474/ecwid-api#7]
![image](https://user-images.githubusercontent.com/3593514/81813628-c1c76980-9538-11ea-8c79-aac079bea639.png)

Hi, When I build this using webpack I see this issue with ecwid module. Could you please check it.

**Comment by mrmaksymivanov** [comment]
Hi
Are you trying to use it in browser? This module intended to be used in NodeJS environment. You probably need to set `target: node` if you're building your app with Webpack.

**Comment by Femina** [comment]
Yes, even though I set a `target: node`, I see errors when we build with Webpack.
